#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.2.11f1_5f859a4cfee5"
#define UNITY_VERSION_FULL_NICE "2019.2.11f1 (5f859a4cfee5)"
#define UNITY_VERSION_BLD 6260122
#define UNITY_VERSION_DATE 1571866552
#define UNITY_VERSION_WIN "2019.2.11.6260122"
#define UNITY_VERSION_BRANCH "2019.2/staging"
